// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	fmt "fmt"

	mock "github.com/stretchr/testify/mock"
)

// InvalidEmailAddressError is an autogenerated mock type for the InvalidEmailAddressError type
type InvalidEmailAddressError struct {
	mock.Mock
}

type InvalidEmailAddressError_Expecter struct {
	mock *mock.Mock
}

func (_m *InvalidEmailAddressError) EXPECT() *InvalidEmailAddressError_Expecter {
	return &InvalidEmailAddressError_Expecter{mock: &_m.Mock}
}

// Cause provides a mock function with no fields
func (_m *InvalidEmailAddressError) Cause() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvalidEmailAddressError_Cause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cause'
type InvalidEmailAddressError_Cause_Call struct {
	*mock.Call
}

// Cause is a helper method to define mock.On call
func (_e *InvalidEmailAddressError_Expecter) Cause() *InvalidEmailAddressError_Cause_Call {
	return &InvalidEmailAddressError_Cause_Call{Call: _e.mock.On("Cause")}
}

func (_c *InvalidEmailAddressError_Cause_Call) Run(run func()) *InvalidEmailAddressError_Cause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InvalidEmailAddressError_Cause_Call) Return(_a0 error) *InvalidEmailAddressError_Cause_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvalidEmailAddressError_Cause_Call) RunAndReturn(run func() error) *InvalidEmailAddressError_Cause_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with no fields
func (_m *InvalidEmailAddressError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// InvalidEmailAddressError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type InvalidEmailAddressError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *InvalidEmailAddressError_Expecter) Error() *InvalidEmailAddressError_Error_Call {
	return &InvalidEmailAddressError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *InvalidEmailAddressError_Error_Call) Run(run func()) *InvalidEmailAddressError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InvalidEmailAddressError_Error_Call) Return(_a0 string) *InvalidEmailAddressError_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvalidEmailAddressError_Error_Call) RunAndReturn(run func() string) *InvalidEmailAddressError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Format provides a mock function with given fields: f, verb
func (_m *InvalidEmailAddressError) Format(f fmt.State, verb rune) {
	_m.Called(f, verb)
}

// InvalidEmailAddressError_Format_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Format'
type InvalidEmailAddressError_Format_Call struct {
	*mock.Call
}

// Format is a helper method to define mock.On call
//   - f fmt.State
//   - verb rune
func (_e *InvalidEmailAddressError_Expecter) Format(f interface{}, verb interface{}) *InvalidEmailAddressError_Format_Call {
	return &InvalidEmailAddressError_Format_Call{Call: _e.mock.On("Format", f, verb)}
}

func (_c *InvalidEmailAddressError_Format_Call) Run(run func(f fmt.State, verb rune)) *InvalidEmailAddressError_Format_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(fmt.State), args[1].(rune))
	})
	return _c
}

func (_c *InvalidEmailAddressError_Format_Call) Return() *InvalidEmailAddressError_Format_Call {
	_c.Call.Return()
	return _c
}

func (_c *InvalidEmailAddressError_Format_Call) RunAndReturn(run func(fmt.State, rune)) *InvalidEmailAddressError_Format_Call {
	_c.Run(run)
	return _c
}

// Message provides a mock function with no fields
func (_m *InvalidEmailAddressError) Message() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// InvalidEmailAddressError_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type InvalidEmailAddressError_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *InvalidEmailAddressError_Expecter) Message() *InvalidEmailAddressError_Message_Call {
	return &InvalidEmailAddressError_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *InvalidEmailAddressError_Message_Call) Run(run func()) *InvalidEmailAddressError_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InvalidEmailAddressError_Message_Call) Return(_a0 string) *InvalidEmailAddressError_Message_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvalidEmailAddressError_Message_Call) RunAndReturn(run func() string) *InvalidEmailAddressError_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *InvalidEmailAddressError) Status() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// InvalidEmailAddressError_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type InvalidEmailAddressError_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *InvalidEmailAddressError_Expecter) Status() *InvalidEmailAddressError_Status_Call {
	return &InvalidEmailAddressError_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *InvalidEmailAddressError_Status_Call) Run(run func()) *InvalidEmailAddressError_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InvalidEmailAddressError_Status_Call) Return(_a0 int) *InvalidEmailAddressError_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvalidEmailAddressError_Status_Call) RunAndReturn(run func() int) *InvalidEmailAddressError_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function with no fields
func (_m *InvalidEmailAddressError) Unwrap() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvalidEmailAddressError_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type InvalidEmailAddressError_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *InvalidEmailAddressError_Expecter) Unwrap() *InvalidEmailAddressError_Unwrap_Call {
	return &InvalidEmailAddressError_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *InvalidEmailAddressError_Unwrap_Call) Run(run func()) *InvalidEmailAddressError_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InvalidEmailAddressError_Unwrap_Call) Return(_a0 error) *InvalidEmailAddressError_Unwrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvalidEmailAddressError_Unwrap_Call) RunAndReturn(run func() error) *InvalidEmailAddressError_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// isBadRequestError provides a mock function with no fields
func (_m *InvalidEmailAddressError) isBadRequestError() {
	_m.Called()
}

// InvalidEmailAddressError_isBadRequestError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isBadRequestError'
type InvalidEmailAddressError_isBadRequestError_Call struct {
	*mock.Call
}

// isBadRequestError is a helper method to define mock.On call
func (_e *InvalidEmailAddressError_Expecter) isBadRequestError() *InvalidEmailAddressError_isBadRequestError_Call {
	return &InvalidEmailAddressError_isBadRequestError_Call{Call: _e.mock.On("isBadRequestError")}
}

func (_c *InvalidEmailAddressError_isBadRequestError_Call) Run(run func()) *InvalidEmailAddressError_isBadRequestError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InvalidEmailAddressError_isBadRequestError_Call) Return() *InvalidEmailAddressError_isBadRequestError_Call {
	_c.Call.Return()
	return _c
}

func (_c *InvalidEmailAddressError_isBadRequestError_Call) RunAndReturn(run func()) *InvalidEmailAddressError_isBadRequestError_Call {
	_c.Run(run)
	return _c
}

// isCustomError provides a mock function with no fields
func (_m *InvalidEmailAddressError) isCustomError() {
	_m.Called()
}

// InvalidEmailAddressError_isCustomError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isCustomError'
type InvalidEmailAddressError_isCustomError_Call struct {
	*mock.Call
}

// isCustomError is a helper method to define mock.On call
func (_e *InvalidEmailAddressError_Expecter) isCustomError() *InvalidEmailAddressError_isCustomError_Call {
	return &InvalidEmailAddressError_isCustomError_Call{Call: _e.mock.On("isCustomError")}
}

func (_c *InvalidEmailAddressError_isCustomError_Call) Run(run func()) *InvalidEmailAddressError_isCustomError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InvalidEmailAddressError_isCustomError_Call) Return() *InvalidEmailAddressError_isCustomError_Call {
	_c.Call.Return()
	return _c
}

func (_c *InvalidEmailAddressError_isCustomError_Call) RunAndReturn(run func()) *InvalidEmailAddressError_isCustomError_Call {
	_c.Run(run)
	return _c
}

// NewInvalidEmailAddressError creates a new instance of InvalidEmailAddressError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvalidEmailAddressError(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvalidEmailAddressError {
	mock := &InvalidEmailAddressError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
