// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	fmt "fmt"

	mock "github.com/stretchr/testify/mock"
)

// OrderNotFoundError is an autogenerated mock type for the OrderNotFoundError type
type OrderNotFoundError struct {
	mock.Mock
}

type OrderNotFoundError_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderNotFoundError) EXPECT() *OrderNotFoundError_Expecter {
	return &OrderNotFoundError_Expecter{mock: &_m.Mock}
}

// Cause provides a mock function with no fields
func (_m *OrderNotFoundError) Cause() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderNotFoundError_Cause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cause'
type OrderNotFoundError_Cause_Call struct {
	*mock.Call
}

// Cause is a helper method to define mock.On call
func (_e *OrderNotFoundError_Expecter) Cause() *OrderNotFoundError_Cause_Call {
	return &OrderNotFoundError_Cause_Call{Call: _e.mock.On("Cause")}
}

func (_c *OrderNotFoundError_Cause_Call) Run(run func()) *OrderNotFoundError_Cause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderNotFoundError_Cause_Call) Return(_a0 error) *OrderNotFoundError_Cause_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderNotFoundError_Cause_Call) RunAndReturn(run func() error) *OrderNotFoundError_Cause_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with no fields
func (_m *OrderNotFoundError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderNotFoundError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type OrderNotFoundError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *OrderNotFoundError_Expecter) Error() *OrderNotFoundError_Error_Call {
	return &OrderNotFoundError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *OrderNotFoundError_Error_Call) Run(run func()) *OrderNotFoundError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderNotFoundError_Error_Call) Return(_a0 string) *OrderNotFoundError_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderNotFoundError_Error_Call) RunAndReturn(run func() string) *OrderNotFoundError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Format provides a mock function with given fields: f, verb
func (_m *OrderNotFoundError) Format(f fmt.State, verb rune) {
	_m.Called(f, verb)
}

// OrderNotFoundError_Format_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Format'
type OrderNotFoundError_Format_Call struct {
	*mock.Call
}

// Format is a helper method to define mock.On call
//   - f fmt.State
//   - verb rune
func (_e *OrderNotFoundError_Expecter) Format(f interface{}, verb interface{}) *OrderNotFoundError_Format_Call {
	return &OrderNotFoundError_Format_Call{Call: _e.mock.On("Format", f, verb)}
}

func (_c *OrderNotFoundError_Format_Call) Run(run func(f fmt.State, verb rune)) *OrderNotFoundError_Format_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(fmt.State), args[1].(rune))
	})
	return _c
}

func (_c *OrderNotFoundError_Format_Call) Return() *OrderNotFoundError_Format_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderNotFoundError_Format_Call) RunAndReturn(run func(fmt.State, rune)) *OrderNotFoundError_Format_Call {
	_c.Run(run)
	return _c
}

// Message provides a mock function with no fields
func (_m *OrderNotFoundError) Message() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderNotFoundError_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type OrderNotFoundError_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *OrderNotFoundError_Expecter) Message() *OrderNotFoundError_Message_Call {
	return &OrderNotFoundError_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *OrderNotFoundError_Message_Call) Run(run func()) *OrderNotFoundError_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderNotFoundError_Message_Call) Return(_a0 string) *OrderNotFoundError_Message_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderNotFoundError_Message_Call) RunAndReturn(run func() string) *OrderNotFoundError_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *OrderNotFoundError) Status() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// OrderNotFoundError_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type OrderNotFoundError_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *OrderNotFoundError_Expecter) Status() *OrderNotFoundError_Status_Call {
	return &OrderNotFoundError_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *OrderNotFoundError_Status_Call) Run(run func()) *OrderNotFoundError_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderNotFoundError_Status_Call) Return(_a0 int) *OrderNotFoundError_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderNotFoundError_Status_Call) RunAndReturn(run func() int) *OrderNotFoundError_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function with no fields
func (_m *OrderNotFoundError) Unwrap() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderNotFoundError_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type OrderNotFoundError_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *OrderNotFoundError_Expecter) Unwrap() *OrderNotFoundError_Unwrap_Call {
	return &OrderNotFoundError_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *OrderNotFoundError_Unwrap_Call) Run(run func()) *OrderNotFoundError_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderNotFoundError_Unwrap_Call) Return(_a0 error) *OrderNotFoundError_Unwrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderNotFoundError_Unwrap_Call) RunAndReturn(run func() error) *OrderNotFoundError_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// isCustomError provides a mock function with no fields
func (_m *OrderNotFoundError) isCustomError() {
	_m.Called()
}

// OrderNotFoundError_isCustomError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isCustomError'
type OrderNotFoundError_isCustomError_Call struct {
	*mock.Call
}

// isCustomError is a helper method to define mock.On call
func (_e *OrderNotFoundError_Expecter) isCustomError() *OrderNotFoundError_isCustomError_Call {
	return &OrderNotFoundError_isCustomError_Call{Call: _e.mock.On("isCustomError")}
}

func (_c *OrderNotFoundError_isCustomError_Call) Run(run func()) *OrderNotFoundError_isCustomError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderNotFoundError_isCustomError_Call) Return() *OrderNotFoundError_isCustomError_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderNotFoundError_isCustomError_Call) RunAndReturn(run func()) *OrderNotFoundError_isCustomError_Call {
	_c.Run(run)
	return _c
}

// isNotFoundError provides a mock function with no fields
func (_m *OrderNotFoundError) isNotFoundError() {
	_m.Called()
}

// OrderNotFoundError_isNotFoundError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isNotFoundError'
type OrderNotFoundError_isNotFoundError_Call struct {
	*mock.Call
}

// isNotFoundError is a helper method to define mock.On call
func (_e *OrderNotFoundError_Expecter) isNotFoundError() *OrderNotFoundError_isNotFoundError_Call {
	return &OrderNotFoundError_isNotFoundError_Call{Call: _e.mock.On("isNotFoundError")}
}

func (_c *OrderNotFoundError_isNotFoundError_Call) Run(run func()) *OrderNotFoundError_isNotFoundError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderNotFoundError_isNotFoundError_Call) Return() *OrderNotFoundError_isNotFoundError_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderNotFoundError_isNotFoundError_Call) RunAndReturn(run func()) *OrderNotFoundError_isNotFoundError_Call {
	_c.Run(run)
	return _c
}

// NewOrderNotFoundError creates a new instance of OrderNotFoundError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderNotFoundError(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderNotFoundError {
	mock := &OrderNotFoundError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
