// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	fmt "fmt"

	mock "github.com/stretchr/testify/mock"
)

// OrderShopItemsRequiredError is an autogenerated mock type for the OrderShopItemsRequiredError type
type OrderShopItemsRequiredError struct {
	mock.Mock
}

type OrderShopItemsRequiredError_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderShopItemsRequiredError) EXPECT() *OrderShopItemsRequiredError_Expecter {
	return &OrderShopItemsRequiredError_Expecter{mock: &_m.Mock}
}

// Cause provides a mock function with no fields
func (_m *OrderShopItemsRequiredError) Cause() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderShopItemsRequiredError_Cause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cause'
type OrderShopItemsRequiredError_Cause_Call struct {
	*mock.Call
}

// Cause is a helper method to define mock.On call
func (_e *OrderShopItemsRequiredError_Expecter) Cause() *OrderShopItemsRequiredError_Cause_Call {
	return &OrderShopItemsRequiredError_Cause_Call{Call: _e.mock.On("Cause")}
}

func (_c *OrderShopItemsRequiredError_Cause_Call) Run(run func()) *OrderShopItemsRequiredError_Cause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderShopItemsRequiredError_Cause_Call) Return(_a0 error) *OrderShopItemsRequiredError_Cause_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderShopItemsRequiredError_Cause_Call) RunAndReturn(run func() error) *OrderShopItemsRequiredError_Cause_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with no fields
func (_m *OrderShopItemsRequiredError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderShopItemsRequiredError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type OrderShopItemsRequiredError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *OrderShopItemsRequiredError_Expecter) Error() *OrderShopItemsRequiredError_Error_Call {
	return &OrderShopItemsRequiredError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *OrderShopItemsRequiredError_Error_Call) Run(run func()) *OrderShopItemsRequiredError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderShopItemsRequiredError_Error_Call) Return(_a0 string) *OrderShopItemsRequiredError_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderShopItemsRequiredError_Error_Call) RunAndReturn(run func() string) *OrderShopItemsRequiredError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Format provides a mock function with given fields: f, verb
func (_m *OrderShopItemsRequiredError) Format(f fmt.State, verb rune) {
	_m.Called(f, verb)
}

// OrderShopItemsRequiredError_Format_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Format'
type OrderShopItemsRequiredError_Format_Call struct {
	*mock.Call
}

// Format is a helper method to define mock.On call
//   - f fmt.State
//   - verb rune
func (_e *OrderShopItemsRequiredError_Expecter) Format(f interface{}, verb interface{}) *OrderShopItemsRequiredError_Format_Call {
	return &OrderShopItemsRequiredError_Format_Call{Call: _e.mock.On("Format", f, verb)}
}

func (_c *OrderShopItemsRequiredError_Format_Call) Run(run func(f fmt.State, verb rune)) *OrderShopItemsRequiredError_Format_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(fmt.State), args[1].(rune))
	})
	return _c
}

func (_c *OrderShopItemsRequiredError_Format_Call) Return() *OrderShopItemsRequiredError_Format_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderShopItemsRequiredError_Format_Call) RunAndReturn(run func(fmt.State, rune)) *OrderShopItemsRequiredError_Format_Call {
	_c.Run(run)
	return _c
}

// Message provides a mock function with no fields
func (_m *OrderShopItemsRequiredError) Message() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderShopItemsRequiredError_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type OrderShopItemsRequiredError_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *OrderShopItemsRequiredError_Expecter) Message() *OrderShopItemsRequiredError_Message_Call {
	return &OrderShopItemsRequiredError_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *OrderShopItemsRequiredError_Message_Call) Run(run func()) *OrderShopItemsRequiredError_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderShopItemsRequiredError_Message_Call) Return(_a0 string) *OrderShopItemsRequiredError_Message_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderShopItemsRequiredError_Message_Call) RunAndReturn(run func() string) *OrderShopItemsRequiredError_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *OrderShopItemsRequiredError) Status() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// OrderShopItemsRequiredError_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type OrderShopItemsRequiredError_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *OrderShopItemsRequiredError_Expecter) Status() *OrderShopItemsRequiredError_Status_Call {
	return &OrderShopItemsRequiredError_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *OrderShopItemsRequiredError_Status_Call) Run(run func()) *OrderShopItemsRequiredError_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderShopItemsRequiredError_Status_Call) Return(_a0 int) *OrderShopItemsRequiredError_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderShopItemsRequiredError_Status_Call) RunAndReturn(run func() int) *OrderShopItemsRequiredError_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function with no fields
func (_m *OrderShopItemsRequiredError) Unwrap() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderShopItemsRequiredError_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type OrderShopItemsRequiredError_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *OrderShopItemsRequiredError_Expecter) Unwrap() *OrderShopItemsRequiredError_Unwrap_Call {
	return &OrderShopItemsRequiredError_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *OrderShopItemsRequiredError_Unwrap_Call) Run(run func()) *OrderShopItemsRequiredError_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderShopItemsRequiredError_Unwrap_Call) Return(_a0 error) *OrderShopItemsRequiredError_Unwrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderShopItemsRequiredError_Unwrap_Call) RunAndReturn(run func() error) *OrderShopItemsRequiredError_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// isBadRequestError provides a mock function with no fields
func (_m *OrderShopItemsRequiredError) isBadRequestError() {
	_m.Called()
}

// OrderShopItemsRequiredError_isBadRequestError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isBadRequestError'
type OrderShopItemsRequiredError_isBadRequestError_Call struct {
	*mock.Call
}

// isBadRequestError is a helper method to define mock.On call
func (_e *OrderShopItemsRequiredError_Expecter) isBadRequestError() *OrderShopItemsRequiredError_isBadRequestError_Call {
	return &OrderShopItemsRequiredError_isBadRequestError_Call{Call: _e.mock.On("isBadRequestError")}
}

func (_c *OrderShopItemsRequiredError_isBadRequestError_Call) Run(run func()) *OrderShopItemsRequiredError_isBadRequestError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderShopItemsRequiredError_isBadRequestError_Call) Return() *OrderShopItemsRequiredError_isBadRequestError_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderShopItemsRequiredError_isBadRequestError_Call) RunAndReturn(run func()) *OrderShopItemsRequiredError_isBadRequestError_Call {
	_c.Run(run)
	return _c
}

// isCustomError provides a mock function with no fields
func (_m *OrderShopItemsRequiredError) isCustomError() {
	_m.Called()
}

// OrderShopItemsRequiredError_isCustomError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isCustomError'
type OrderShopItemsRequiredError_isCustomError_Call struct {
	*mock.Call
}

// isCustomError is a helper method to define mock.On call
func (_e *OrderShopItemsRequiredError_Expecter) isCustomError() *OrderShopItemsRequiredError_isCustomError_Call {
	return &OrderShopItemsRequiredError_isCustomError_Call{Call: _e.mock.On("isCustomError")}
}

func (_c *OrderShopItemsRequiredError_isCustomError_Call) Run(run func()) *OrderShopItemsRequiredError_isCustomError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderShopItemsRequiredError_isCustomError_Call) Return() *OrderShopItemsRequiredError_isCustomError_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderShopItemsRequiredError_isCustomError_Call) RunAndReturn(run func()) *OrderShopItemsRequiredError_isCustomError_Call {
	_c.Run(run)
	return _c
}

// NewOrderShopItemsRequiredError creates a new instance of OrderShopItemsRequiredError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderShopItemsRequiredError(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderShopItemsRequiredError {
	mock := &OrderShopItemsRequiredError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
